# Generated by Django 4.2.9 on 2024-01-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_todo_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="images")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "todo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="app.todo",
                    ),
                ),
            ],
        ),
    ]
