# Generated by Django 4.2.9 on 2024-01-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_category_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
