# Generated by Django 4.2.10 on 2024-02-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("htmx", "0003_alter_variantoption_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="htmx.category",
            ),
        ),
        migrations.AlterField(
            model_name="variantoption",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_options",
                to="htmx.option",
            ),
        ),
        migrations.AlterField(
            model_name="variantoption",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="htmx.productvariant",
            ),
        ),
    ]
