# Generated by Django 4.2.10 on 2024-02-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("htmx", "0004_option_category_alter_variantoption_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantoption",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_options",
                to="htmx.productvariant",
            ),
        ),
    ]
