# Generated by Django 4.2.10 on 2024-02-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("htmx", "0005_alter_variantoption_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variants",
                to="htmx.product",
            ),
        ),
    ]
