# Generated by Django 4.2.9 on 2024-01-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stoke",
            field=models.IntegerField(default=0),
        ),
    ]
