# Generated by Django 4.2.9 on 2024-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(related_name="products", to="app.tag"),
        ),
    ]
