# Generated by Django 4.2.9 on 2024-01-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_tag_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stoke",
            new_name="stock",
        ),
    ]
