# Generated by Django 4.2.9 on 2024-01-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_product_tags_tag_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="products",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(related_name="products", to="app.tag"),
        ),
    ]
