# Generated by Django 4.2.13 on 2024-06-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapi", "0002_child_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(related_name="products", to="testapi.tag"),
        ),
    ]
